package io.github.team2.Game.entity;

public enum EntityType {
    UNDEFINED, PLAYER, ENEMY, DROP, BUCKET, CIRCLE, TRIANGLE, POWERUP, RECYCLABLE, NON_RECYCLABLE, RECYCLING_BIN, ALIEN, PIPE,
     PLANET
}
